package clientstate

import (
	"testing"

	"github.com/sandertv/gophertunnel/minecraft/protocol/packet"
)

// triage classifies a clientbound packet's relationship to a server swap.
type triage uint8

const (
	// triageTracked: Observe mirrors it and ClearPackets removes it.
	triageTracked triage = iota
	// triageSwept: state ClearPackets clears unconditionally (titles, forms, inventory).
	triageSwept
	// triageRestored: re-derived from GameData by the swap flow, or re-established by
	// the replacement's own join sequence (world content, registries, rules).
	triageRestored
	// triageGap: outlives a swap but is deliberately untracked (camera, HUD, fog, debug
	// shapes, looping sounds); a swap flow owns whichever of these it cares about.
	triageGap
	// triageTransient: leaves no client-visible state that outlives a swap.
	triageTransient
)

var triageNames = map[triage]string{
	triageTracked: "tracked", triageSwept: "swept", triageRestored: "restored",
	triageGap: "gap", triageTransient: "transient",
}

// serverPacketTriage classifies every packet the server pool can produce, so a protocol
// bump that adds a clientbound packet fails TestServerPoolTriaged until someone decides
// whether the new packet's state must be tracked.
var serverPacketTriage = map[uint32]triage{
	packet.IDAddActor:                           triageTracked,
	packet.IDAddItemActor:                       triageTracked,
	packet.IDAddPainting:                        triageTracked,
	packet.IDAddPlayer:                          triageTracked,
	packet.IDAddVolumeEntity:                    triageTracked,
	packet.IDBossEvent:                          triageTracked,
	packet.IDContainerClose:                     triageTracked,
	packet.IDContainerOpen:                      triageTracked,
	packet.IDMobEffect:                          triageTracked,
	packet.IDPlayerList:                         triageTracked,
	packet.IDRemoveActor:                        triageTracked,
	packet.IDRemoveObjective:                    triageTracked,
	packet.IDRemoveVolumeEntity:                 triageTracked,
	packet.IDSetDisplayObjective:                triageTracked,
	packet.IDInventoryContent:                   triageSwept,
	packet.IDInventorySlot:                      triageSwept,
	packet.IDModalFormRequest:                   triageSwept,
	packet.IDSetTitle:                           triageSwept,
	packet.IDAvailableActorIdentifiers:          triageRestored,
	packet.IDAvailableCommands:                  triageRestored,
	packet.IDBiomeDefinitionList:                triageRestored,
	packet.IDBlockActorData:                     triageRestored,
	packet.IDChangeDimension:                    triageRestored,
	packet.IDChunkRadiusUpdated:                 triageRestored,
	packet.IDClientboundUpdateSoundData:         triageRestored,
	packet.IDCraftingData:                       triageRestored,
	packet.IDCreativeContent:                    triageRestored,
	packet.IDDimensionData:                      triageRestored,
	packet.IDFeatureRegistry:                    triageRestored,
	packet.IDGameRulesChanged:                   triageRestored,
	packet.IDItemRegistry:                       triageRestored,
	packet.IDLevelChunk:                         triageRestored,
	packet.IDNetworkChunkPublisherUpdate:        triageRestored,
	packet.IDSetCommandsEnabled:                 triageRestored,
	packet.IDSetDifficulty:                      triageRestored,
	packet.IDSetPlayerGameType:                  triageRestored,
	packet.IDSetSpawnPosition:                   triageRestored,
	packet.IDSetTime:                            triageRestored,
	packet.IDStartGame:                          triageRestored,
	packet.IDSubChunk:                           triageRestored,
	packet.IDSyncActorProperty:                  triageRestored,
	packet.IDSyncWorldClocks:                    triageRestored,
	packet.IDTrimData:                           triageRestored,
	packet.IDUnlockedRecipes:                    triageRestored,
	packet.IDUpdateAbilities:                    triageRestored,
	packet.IDUpdateAdventureSettings:            triageRestored,
	packet.IDUpdateBlock:                        triageRestored,
	packet.IDUpdateBlockSynced:                  triageRestored,
	packet.IDUpdatePlayerGameType:               triageRestored,
	packet.IDUpdateSoftEnum:                     triageRestored,
	packet.IDUpdateSubChunkBlocks:               triageRestored,
	packet.IDCameraAimAssist:                    triageGap,
	packet.IDCameraAimAssistActorPriority:       triageGap,
	packet.IDCameraAimAssistPresets:             triageGap,
	packet.IDCameraInstruction:                  triageGap,
	packet.IDCameraPresets:                      triageGap,
	packet.IDCameraSpline:                       triageGap,
	packet.IDClientBoundControlSchemeSet:        triageGap,
	packet.IDClientBoundDataDrivenUIShowScreen:  triageGap,
	packet.IDClientBoundDataStore:               triageGap,
	packet.IDClientBoundDebugRenderer:           triageGap,
	packet.IDClientBoundTextureShift:            triageGap,
	packet.IDClientCameraAimAssist:              triageGap,
	packet.IDGraphicsOverrideParameter:          triageGap,
	packet.IDLocatorBar:                         triageGap,
	packet.IDNPCDialogue:                        triageGap,
	packet.IDPlaySound:                          triageGap,
	packet.IDPlayerFog:                          triageGap,
	packet.IDPrimitiveShapes:                    triageGap,
	packet.IDSetHud:                             triageGap,
	packet.IDUpdateClientInputLocks:             triageGap,
	packet.IDVoxelShapes:                        triageGap,
	packet.IDActorEvent:                         triageTransient,
	packet.IDActorPickRequest:                   triageTransient,
	packet.IDAddBehaviourTree:                   triageTransient,
	packet.IDAdventureSettings:                  triageTransient,
	packet.IDAgentAction:                        triageTransient,
	packet.IDAgentAnimation:                     triageTransient,
	packet.IDAnimate:                            triageTransient,
	packet.IDAnimateEntity:                      triageTransient,
	packet.IDAnvilDamage:                        triageTransient,
	packet.IDAutomationClientConnect:            triageTransient,
	packet.IDAwardAchievement:                   triageTransient,
	packet.IDBlockEvent:                         triageTransient,
	packet.IDBlockPickRequest:                   triageTransient,
	packet.IDBookEdit:                           triageTransient,
	packet.IDCamera:                             triageTransient,
	packet.IDCameraShake:                        triageTransient,
	packet.IDChangeMobProperty:                  triageTransient,
	packet.IDClientBoundAttributeLayerSync:      triageTransient,
	packet.IDClientBoundCloseForm:               triageTransient,
	packet.IDClientBoundDataDrivenUICloseScreen: triageTransient,
	packet.IDClientBoundDataDrivenUIReload:      triageTransient,
	packet.IDClientBoundMapItemData:             triageTransient,
	packet.IDClientCacheBlobStatus:              triageTransient,
	packet.IDClientCacheMissResponse:            triageTransient,
	packet.IDClientCacheStatus:                  triageTransient,
	packet.IDClientCheatAbility:                 triageTransient,
	packet.IDClientMovementPredictionSync:       triageTransient,
	packet.IDClientStartItemCooldown:            triageTransient,
	packet.IDClientToServerHandshake:            triageTransient,
	packet.IDCodeBuilder:                        triageTransient,
	packet.IDCodeBuilderSource:                  triageTransient,
	packet.IDCommandBlockUpdate:                 triageTransient,
	packet.IDCommandOutput:                      triageTransient,
	packet.IDCommandRequest:                     triageTransient,
	packet.IDCompletedUsingItem:                 triageTransient,
	packet.IDContainerRegistryCleanup:           triageTransient,
	packet.IDContainerSetData:                   triageTransient,
	packet.IDCorrectPlayerMovePrediction:        triageTransient,
	packet.IDCreatePhoto:                        triageTransient,
	packet.IDCurrentStructureFeature:            triageTransient,
	packet.IDDeathInfo:                          triageTransient,
	packet.IDDebugInfo:                          triageTransient,
	packet.IDDisconnect:                         triageTransient,
	packet.IDEditorNetwork:                      triageTransient,
	packet.IDEducationResourceURI:               triageTransient,
	packet.IDEducationSettings:                  triageTransient,
	packet.IDEmote:                              triageTransient,
	packet.IDEmoteList:                          triageTransient,
	packet.IDEvent:                              triageTransient,
	packet.IDFilterText:                         triageTransient,
	packet.IDGUIDataPickItem:                    triageTransient,
	packet.IDGameTestRequest:                    triageTransient,
	packet.IDGameTestResults:                    triageTransient,
	packet.IDHurtArmour:                         triageTransient,
	packet.IDInteract:                           triageTransient,
	packet.IDInventoryTransaction:               triageTransient,
	packet.IDItemStackRequest:                   triageTransient,
	packet.IDItemStackResponse:                  triageTransient,
	packet.IDJigsawStructureData:                triageTransient,
	packet.IDLabTable:                           triageTransient,
	packet.IDLecternUpdate:                      triageTransient,
	packet.IDLessonProgress:                     triageTransient,
	packet.IDLevelEvent:                         triageTransient,
	packet.IDLevelEventGeneric:                  triageTransient,
	packet.IDLevelSoundEvent:                    triageTransient,
	packet.IDLogin:                              triageTransient,
	packet.IDMapCreateLockedCopy:                triageTransient,
	packet.IDMapInfoRequest:                     triageTransient,
	packet.IDMobArmourEquipment:                 triageTransient,
	packet.IDMobEquipment:                       triageTransient,
	packet.IDModalFormResponse:                  triageTransient,
	packet.IDMotionPredictionHints:              triageTransient,
	packet.IDMoveActorAbsolute:                  triageTransient,
	packet.IDMoveActorDelta:                     triageTransient,
	packet.IDMovePlayer:                         triageTransient,
	packet.IDMovementEffect:                     triageTransient,
	packet.IDMultiPlayerSettings:                triageTransient,
	packet.IDNPCRequest:                         triageTransient,
	packet.IDNetworkSettings:                    triageTransient,
	packet.IDNetworkStackLatency:                triageTransient,
	packet.IDOnScreenTextureAnimation:           triageTransient,
	packet.IDOpenSign:                           triageTransient,
	packet.IDPacketViolationWarning:             triageTransient,
	packet.IDPhotoInfoRequest:                   triageTransient,
	packet.IDPhotoTransfer:                      triageTransient,
	packet.IDPlayStatus:                         triageTransient,
	packet.IDPlayerAction:                       triageTransient,
	packet.IDPlayerArmourDamage:                 triageTransient,
	packet.IDPlayerAuthInput:                    triageTransient,
	packet.IDPlayerEnchantOptions:               triageTransient,
	packet.IDPlayerHotBar:                       triageTransient,
	packet.IDPlayerLocation:                     triageTransient,
	packet.IDPlayerSkin:                         triageTransient,
	packet.IDPlayerToggleCrafterSlotRequest:     triageTransient,
	packet.IDPlayerUpdateEntityOverrides:        triageTransient,
	packet.IDPlayerVideoCapture:                 triageTransient,
	packet.IDPositionTrackingDBClientRequest:    triageTransient,
	packet.IDPositionTrackingDBServerBroadcast:  triageTransient,
	packet.IDPurchaseReceipt:                    triageTransient,
	packet.IDRefreshEntitlements:                triageTransient,
	packet.IDRequestAbility:                     triageTransient,
	packet.IDRequestChunkRadius:                 triageTransient,
	packet.IDRequestNetworkSettings:             triageTransient,
	packet.IDRequestPermissions:                 triageTransient,
	packet.IDResourcePackChunkData:              triageTransient,
	packet.IDResourcePackChunkRequest:           triageTransient,
	packet.IDResourcePackClientResponse:         triageTransient,
	packet.IDResourcePackDataInfo:               triageTransient,
	packet.IDResourcePackStack:                  triageTransient,
	packet.IDResourcePacksInfo:                  triageTransient,
	packet.IDRespawn:                            triageTransient,
	packet.IDScriptCustomEvent:                  triageTransient,
	packet.IDScriptMessage:                      triageTransient,
	packet.IDSendPartyDestinationCookie:         triageTransient,
	packet.IDServerBoundDiagnostics:             triageTransient,
	packet.IDServerBoundLoadingScreen:           triageTransient,
	packet.IDServerBoundPackSettingChange:       triageTransient,
	packet.IDServerPlayerPostMovePosition:       triageTransient,
	packet.IDServerPresenceInfo:                 triageTransient,
	packet.IDServerSettingsRequest:              triageTransient,
	packet.IDServerSettingsResponse:             triageTransient,
	packet.IDServerStats:                        triageTransient,
	packet.IDServerStoreInfo:                    triageTransient,
	packet.IDServerToClientHandshake:            triageTransient,
	packet.IDSetActorData:                       triageTransient,
	packet.IDSetActorLink:                       triageTransient,
	packet.IDSetActorMotion:                     triageTransient,
	packet.IDSetDefaultGameType:                 triageTransient,
	packet.IDSetHealth:                          triageTransient,
	packet.IDSetLastHurtBy:                      triageTransient,
	packet.IDSetLocalPlayerAsInitialised:        triageTransient,
	packet.IDSetPlayerInventoryOptions:          triageTransient,
	packet.IDSetScore:                           triageTransient,
	packet.IDSetScoreboardIdentity:              triageTransient,
	packet.IDSettingsCommand:                    triageTransient,
	packet.IDShowCredits:                        triageTransient,
	packet.IDShowProfile:                        triageTransient,
	packet.IDShowStoreOffer:                     triageTransient,
	packet.IDSimpleEvent:                        triageTransient,
	packet.IDSimulationType:                     triageTransient,
	packet.IDSpawnExperienceOrb:                 triageTransient,
	packet.IDSpawnParticleEffect:                triageTransient,
	packet.IDStopSound:                          triageTransient,
	packet.IDStructureBlockUpdate:               triageTransient,
	packet.IDStructureTemplateDataRequest:       triageTransient,
	packet.IDStructureTemplateDataResponse:      triageTransient,
	packet.IDSubChunkRequest:                    triageTransient,
	packet.IDSubClientLogin:                     triageTransient,
	packet.IDTakeItemActor:                      triageTransient,
	packet.IDText:                               triageTransient,
	packet.IDTickingAreasLoadStatus:             triageTransient,
	packet.IDToastRequest:                       triageTransient,
	packet.IDTransfer:                           triageTransient,
	packet.IDUpdateAttributes:                   triageTransient,
	packet.IDUpdateClientOptions:                triageTransient,
	packet.IDUpdateEquip:                        triageTransient,
	packet.IDUpdateTrade:                        triageTransient,
}

// A new server-pool packet must be classified, and the manifest must agree with Tracked.
func TestServerPoolTriaged(t *testing.T) {
	pool := packet.NewServerPool()
	for id, mk := range pool {
		tri, ok := serverPacketTriage[id]
		if !ok {
			t.Errorf("%T (ID %d) is not classified in serverPacketTriage; if it creates client state that outlives a server swap, track it", mk(), id)
			continue
		}
		if got := Tracked(mk()); got != (tri == triageTracked) {
			t.Errorf("Tracked(%T) = %t, but the manifest classifies it %q", mk(), got, triageNames[tri])
		}
	}
	for id := range serverPacketTriage {
		if _, ok := pool[id]; !ok {
			t.Errorf("manifest entry for packet ID %d is no longer in the server pool; remove it", id)
		}
	}
}
